
services:

  redis:
      image: "redis:alpine"
      # hostname: redis
      container_name: movie-game-redis
      ports:
        - "6379:6379"
      networks: 
        - central_bridge


networks:
  central_bridge:
    driver: bridge