
services:
  back:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    container_name: movie-game-back
    image: hichamsbihi/getting-started:1.0.0-back
    user: root
    ports:
      - 3100:3100
    env_file:
      - ./back/.env
    networks: 
      - central_bridge

  nginx:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    container_name: nginx_server
    image: hichamsbihi/getting-started:1.0.0-front
    ports: 
      - 80:80
    networks: 
      - central_bridge
 
  redis:
    image: "redis:alpine"
    # hostname: redis
    container_name: movie-game-redis
    ports:
      - "6379:6379"
    networks: 
      - central_bridge


networks:
  central_bridge:
    driver: bridge